// PRODUCTOS - Solo los activos (amarillos en el Sheet)
const PRODUCTOS_CONFIG = [
    { nombre: 'PEREJIL AGROEC. [ATADO]', precio: 1000, unidad: 'atado', peso: '50 gr', emoji: '🌿' },
    { nombre: 'ACELGA AGROEC. [ATADO]', precio: 2800, unidad: 'atado', peso: '800 gr', emoji: '🥬' },
    { nombre: 'ACHICORIA [ATADO]', precio: 1200, unidad: 'unidad', peso: '200 gr', emoji: '🥗' },
    { nombre: 'CALABAZA [POR PESO]', precio: 1000, unidad: 'kilo', peso: '1000 gr', emoji: '🎃' },
    { nombre: 'CIBULLETE [ATADO]', precio: 1500, unidad: 'atado', peso: '25 gr', emoji: '🧅' },
    { nombre: 'HOJAS ENSALADA [MEZCLUM] X350GR', precio: 4000, unidad: 'unidad', peso: '350 gr', emoji: '🥗' },
    { nombre: 'HUEVOS DE CAMPO [POR 1/2 DOC.]', precio: 2000, unidad: 'unidad', peso: '1/2 docena', emoji: '🥚' },
    { nombre: 'HUEVOS DE CAMPO [POR 1 DOC.]', precio: 4000, unidad: 'unidad', peso: '1 docena', emoji: '🥚' },
    { nombre: 'HUEVOS DE CAMPO [MAPLE]', precio: 9000, unidad: 'unidad', peso: 'maple', emoji: '🥚' },
    { nombre: 'KALE [ATADO]', precio: 1800, unidad: 'atado', peso: '200 gr', emoji: '🥬' },
    { nombre: 'PLANTIN AROMATICA [M12]', precio: 1800, unidad: 'unidad', peso: '1000 gr', emoji: '🌿' },
    { nombre: 'PLANTIN HUERTA [M12]', precio: 1500, unidad: 'unidad', peso: '1000 gr', emoji: '🪴' },
    { nombre: 'PUERRO AGROEC. [ATADO]', precio: 1800, unidad: 'atado', peso: '500 gr', emoji: '🌿' },
    { nombre: 'RUCULA [MEZCLUM]', precio: 2000, unidad: 'kilo', peso: '350 gr', emoji: '🥗' },
    { nombre: 'RUCULA [ATADO]', precio: 4500, unidad: 'kilo', peso: '200 gr', emoji: '🥗' },
    { nombre: 'OREGANO DESHIDRATADO [POR PESO]', precio: 1800, unidad: 'unidad', peso: '31 gr', emoji: '🌿' },
    { nombre: 'HINOJO [POR UND.]', precio: 2100, unidad: 'unidad', peso: '450 gr', emoji: '🌿' },
    { nombre: 'AJO GIGANTE CHILENO AGROEC. [POR UND.]', precio: 1000, unidad: 'unidad', peso: '60 gr', emoji: '🧄' },
    { nombre: 'ACELGA AGROEC. X 2 [ATADO]', precio: 2500, unidad: 'atado', peso: '800 gr', emoji: '🥬' },
    { nombre: 'ALBAHACA AGROEC. [ATADO]', precio: 2000, unidad: 'atado', peso: '250 gr', emoji: '🌿' },
    { nombre: 'MANDARINAS [POR PESO]', precio: 1500, unidad: 'kilo', peso: '2000 gr', emoji: '🍊' },
];
